cmake_minimum_required(VERSION 3.16)
project(ets2_bridge)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(ets2_msgs REQUIRED)
find_package(std_srvs REQUIRED)
find_package(nlohmann_json REQUIRED)
add_executable(ets2_bridge src/main.cpp)
target_compile_features(ets2_bridge PRIVATE cxx_std_20)
target_include_directories(ets2_bridge PRIVATE ../../common)
target_link_libraries(ets2_bridge nlohmann_json::nlohmann_json)
ament_target_dependencies(ets2_bridge rclcpp std_srvs)
install(TARGETS ets2_bridge DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
install(FILES ../../config/fastdds.xml ../../config/foxglove.yaml DESTINATION share/${PROJECT_NAME}/config)
ament_package()
