cmake_minimum_required(VERSION 3.16)
project(ets2_autonomy)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(ets2_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(nlohmann_json REQUIRED)
add_executable(drive_speed src/gt_drive_node.cpp)
target_compile_features(drive_speed PRIVATE cxx_std_20)
target_link_libraries(drive_speed nlohmann_json::nlohmann_json)
ament_target_dependencies(drive_speed rclcpp ets2_msgs geometry_msgs std_msgs)
install(TARGETS drive_speed DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
ament_package()
